pipeline {
agent any
stages {
stage('Provision infrastructure') {
 steps {
   sh './Actimize-master/Customers/HSBC/ ; terraform init'
   sh './Actimize-master/Customers/HSBC/ ; terraform plan -out=plan'

 }
}
  stage('Approval') {
      steps {
        script {
          def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
        }
      }
    }
stage('TF Apply') {
      steps {
        
          sh './Actimize-master/Customers/HSBC/ ; terraform apply plan'
        
      }
    }
}
}
 
