pipeline {
agent any
stages {
stage('Provision infrastructure') {
 steps {
  environment {
  AWS_ID = credentials("AWS")
  AWS_ACCESS_KEY_ID = "${env.AWS_USR}"
  AWS_SECRET_ACCESS_KEY = "${env.AWS_PSW}"
 }
   sh 'terraform init --var-file=./Actimize-master/Customers/HSBC/hsbc.tfvars ./Actimize-master/Customers/HSBC/'
   sh 'terraform plan --var-file=./Actimize-master/Customers/HSBC/hsbc.tfvars -out=plan  ./Actimize-master/Customers/HSBC/'

 }
}
  stage('Approval') {
      steps {
        script {
          def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
        }
      }
    }
stage('TF Apply') {
      steps {
        
          sh ' terraform apply --var-file=./Actimize-master/Customers/HSBC/hsbc.tfvars   ./Actimize-master/Customers/HSBC/'
        
      }
    }
}
}
 
