pipeline {
agent any
stages {
stage('Checkout project from github') {
   steps {
       sh '/usr/Terra/'
       git branch: 'master',
           url: 'ssh://git@github.com:JyotikaW/Demo.git'

       sh "ls -lat"
   }
}
stage('Provision infrastructure') {
 steps {
   sh '/usr/Terra/Demo/Actimize-master/Customers/HSBC/terraform init'
   sh '/usr/Terra/Demo/Actimize-master/Customers/HSBC/terraform plan -out=plan'

 }
}
  stage('Approval') {
      steps {
        script {
          def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
        }
      }
    }
stage('TF Apply') {
      steps {
        
          sh '/usr/Terra/terraform apply plan'
        
      }
    }
}
}
 
